### ISSUE TITLE
'module "QtWebSockets" is not installed'

### ISSUE THREAD

**Issue by Zeitsperre** [chiyuki0325/lyrica#6]
Hi there,

I'm trying to install this widget in Fedora 40 (KDE Plasma 6) and it doesn't seem to recognize the versions of `QtWebSockets` installed.

My error output is:
```
<home>/.local/share/plasma/plasmoids/ink.chyk.plasmaDesktopLyrics/contents/ui/main.qml:5:1: module "QtWebSockets" is not installed
```

I have installed the following packages and restarted:
- qt5-qtwebsockets
- qt6-qtwebsockets
- qt5-qtwebsockets-devel
- qt6-qtwebsockets-devel
- golang-github-gorilla-websocket-devel

谢谢你！

**Comment by chiyuki0325** [comment]
I'm on Arch Linux and I just installed the qt6-websockets package and then it worked...
Not sure about other distributions...

**Comment by chiyuki0325** [comment]
Just install qt6-qtwebsockets-devel, logout and re-login then it should work.
